# Generated by Django 4.1.7 on 2023-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteka', '0002_actor_genre_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='filmoteka.actor'),
        ),
    ]
