# Generated by Django 4.1.7 on 2023-03-23 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmoteka', '0004_movie_genres_mark_favourite_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='post_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
